---
swagger: "2.0"
info:
  description: "This is a sample server for a Todos API."
  version: "1.0.0"
  title: "Swagger Todos"
  termsOfService: "none"
  contact:
    email: "blainerrichardson@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/v1"
tags:
- name: "todo"
  description: "All potential endpoints refering to Todos."
schemes:
- "http"
paths:
  /todos:
    get:
      tags:
      - "todo"
      summary: "Returns all the todos in the database."
      description: "Returns all the todos in the database."
      operationId: "findTodos"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Todo"
      x-swagger-router-controller: "TodosController"
  /todo:
    post:
      tags:
      - "todo"
      summary: "Inserts a new Todo into the database."
      description: "Inserts a new Todo into the database."
      operationId: "newTodo"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Todo object that needs to be added to the database."
        required: true
        schema:
          $ref: "#/definitions/TodoNew"
      responses:
        200:
          description: "Successful insert."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TodoSuccessfulInsert"
        500:
          description: "Invalid input"
      x-swagger-router-controller: "TodosController"    
definitions:
  Todo:
    type: "object"
    properties:
      _id:
        type: "string"
      completed:
        type: "boolean"
        default: false
      completedAt:
        type: "string"
        default: "null"
      text:
        type: "string"
      __v: 
        type: "integer"
        format: "int32"
    title: "Todo"
    description: "Object with array of multiple todos"
  TodoNew:
    type: "object"
    properties:
      text:
        type: "string"
      completed:
        type: "boolean"
        default: false
    title: "NewTodo"
    description: "Object new todo."
  TodoSuccessfulInsert:
    type: "object"
    properties:
      text:
        type: "string"
      completed:
        type: "boolean"
      completedAt:
        type: "string"
        default: "null"
      _id: 
        type: "string"
    title: "TodoSuccessfulInsert"
    description: "Object new todo."
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
    title: "An uploaded response"
    description: "Describes the result of uploading an image resource"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
